apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-wheelchair-production
  labels:
    app: cv-wheelchair
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cv-wheelchair
  template:
    metadata:
      labels:
        app: cv-wheelchair
    spec:
      containers:
      - name: cv-wheelchair
        image: ghcr.io/${{ github.repository_owner }}/cv_wheelchair:1.0.0
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
