apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-wheelchair-staging
  labels:
    app: cv-wheelchair
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cv-wheelchair
  template:
    metadata:
      labels:
        app: cv-wheelchair
    spec:
      containers:
      - name: cv-wheelchair
        image: ghcr.io/${{ github.repository_owner }}/cv_wheelchair:1.2.1
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health  # Ensure the /health endpoint is exposed by your app
            port: 8000
          initialDelaySeconds: 5  # Delay before checking
          periodSeconds: 10  # Period between checks
          failureThreshold: 2  # Number of failures before considering the container unhealthy
        readinessProbe:
          httpGet:
            path: apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-wheelchair-production
  labels:
    app: cv-wheelchair
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cv-wheelchair
  template:
    metadata:
      labels:
        app: cv-wheelchair
    spec:
      containers:
      - name: cv-wheelchair
        image: ghcr.io/${{ github.repository_owner }}/cv_wheelchair:1.0.0
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: http://localhost:8000/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: http://localhost:8000/health  # Ensures the container is ready before traffic is sent
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3  # Ensures the container is ready before traffic is sent
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
